MODEL:
  NAME: 'seresnext50'
  POOLING_METHOD: 'avg'
  ID_LOSS_TYPE: ''
  FEAT_SIZE: 2048
DATASETS:
  HARD_AUG: 'simple'
INPUT:
  SIZE_TRAIN: '[224, 224]'
  SIZE_TEST: '[224, 224]'
  GRAY_RPO: 0.05
  RE_PROB: 0.5
SOLVER:
  TYPE: 'warmup_cos'
  STEPS: [15, 25]
  MAX_EPOCHS: 60
  WARMUP_EPOCHS: 8
  BASE_LR: 0.04
  CENTER_LR: 0.2
  CENTER_LOSS_WEIGHT: 0.0003
  COSINE_MARGIN: 0.1
  COSINE_SCALE: 40
  IMS_PER_BATCH: 64